from decouple import config

MONGODB_URI = config('MONGODB_URI')
MONGODB_DB = config("MONGODB_DB")
REDIS_MAX_CONNECTIONS = config('REDIS_MAX_CONNECTIONS')
REDIS_MIN_CONNECTIONS = config('REDIS_MIN_CONNECTIONS')
REDIS_HOST = config('REDIS_HOST')
REDIS_PORT = config('REDIS_PORT')